# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get e4-management could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/e4-management/0.1.0"
SRC_URI += "git://github.com/rodar-ascom/e4-management.git;protocol=https;nobranch=1"
SRCREV = "0b11f466f0c1ea252d91e5be3f1d1c3e07dcb580"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+0b11f466f0"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/aho-corasick/1.1.5 \
    crate://crates.io/askama/0.14.0 \
    crate://crates.io/askama_derive/0.14.0 \
    crate://crates.io/askama_parser/0.14.0 \
    crate://crates.io/atomic-waker/1.1.2 \
    crate://crates.io/axum-core/0.5.6 \
    crate://crates.io/axum/0.8.9 \
    crate://crates.io/basic-toml/0.1.10 \
    crate://crates.io/bytes/1.12.1 \
    crate://crates.io/cfg-if/1.0.4 \
    crate://crates.io/form_urlencoded/1.2.2 \
    crate://crates.io/futures-channel/0.3.34 \
    crate://crates.io/futures-core/0.3.34 \
    crate://crates.io/futures-task/0.3.34 \
    crate://crates.io/futures-util/0.3.34 \
    crate://crates.io/http-body-util/0.1.5 \
    crate://crates.io/http-body/1.1.0 \
    crate://crates.io/http/1.5.0 \
    crate://crates.io/httparse/1.10.1 \
    crate://crates.io/httpdate/1.0.3 \
    crate://crates.io/hyper-util/0.1.20 \
    crate://crates.io/hyper/1.11.0 \
    crate://crates.io/itoa/1.0.18 \
    crate://crates.io/lazy_static/1.5.0 \
    crate://crates.io/libc/0.2.189 \
    crate://crates.io/log/0.4.34 \
    crate://crates.io/matchers/0.2.0 \
    crate://crates.io/matchit/0.8.4 \
    crate://crates.io/memchr/2.8.3 \
    crate://crates.io/mime/0.3.17 \
    crate://crates.io/mio/1.2.2 \
    crate://crates.io/nu-ansi-term/0.50.3 \
    crate://crates.io/once_cell/1.21.4 \
    crate://crates.io/percent-encoding/2.3.2 \
    crate://crates.io/pin-project-lite/0.2.17 \
    crate://crates.io/proc-macro2/1.0.107 \
    crate://crates.io/quote/1.0.47 \
    crate://crates.io/regex-automata/0.4.18 \
    crate://crates.io/regex-syntax/0.8.11 \
    crate://crates.io/rustc-hash/2.1.3 \
    crate://crates.io/ryu/1.0.23 \
    crate://crates.io/serde/1.0.229 \
    crate://crates.io/serde_core/1.0.229 \
    crate://crates.io/serde_derive/1.0.229 \
    crate://crates.io/serde_json/1.0.151 \
    crate://crates.io/serde_path_to_error/0.1.20 \
    crate://crates.io/serde_urlencoded/0.7.1 \
    crate://crates.io/sharded-slab/0.1.7 \
    crate://crates.io/slab/0.4.12 \
    crate://crates.io/smallvec/1.15.2 \
    crate://crates.io/socket2/0.6.5 \
    crate://crates.io/syn/2.0.119 \
    crate://crates.io/syn/3.0.4 \
    crate://crates.io/sync_wrapper/1.0.2 \
    crate://crates.io/thread_local/1.1.10 \
    crate://crates.io/tokio-macros/2.7.2 \
    crate://crates.io/tokio/1.53.1 \
    crate://crates.io/tower-layer/0.3.3 \
    crate://crates.io/tower-service/0.3.3 \
    crate://crates.io/tower/0.5.3 \
    crate://crates.io/tracing-attributes/0.1.31 \
    crate://crates.io/tracing-core/0.1.36 \
    crate://crates.io/tracing-log/0.2.0 \
    crate://crates.io/tracing-subscriber/0.3.23 \
    crate://crates.io/tracing/0.1.44 \
    crate://crates.io/unicode-ident/1.0.24 \
    crate://crates.io/valuable/0.1.1 \
    crate://crates.io/wasi/0.11.1+wasi-snapshot-preview1 \
    crate://crates.io/windows-link/0.2.1 \
    crate://crates.io/windows-sys/0.61.2 \
    crate://crates.io/winnow/0.7.15 \
    crate://crates.io/zmij/1.0.23 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

SUMMARY = "e4-management"
HOMEPAGE = "https://github.com/rodar-ascom/e4-management.git"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include e4-management-${PV}.inc
include e4-management.inc
